# Generated by Django 2.2.18 on 2021-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0002_definition_auto_translation_source"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="wordform",
            index=models.Index(
                fields=["inflectional_category"], name="API_wordfor_inflect_a2cc0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wordform",
            index=models.Index(fields=["pos"], name="API_wordfor_pos_b47c18_idx"),
        ),
    ]
