# Generated by Django 4.2.16 on 2024-10-18 18:11

from django.db import migrations
from django.conf import settings

def change_example_to_production_site(apps, schema_editor):
    """
    Changes the example.com site to the current site domain.
    As of 2021-03-11, this is itwewina.altlab.app.
    """
    Site = apps.get_model("sites", "Site")
    site, created = Site.objects.get_or_create(pk=1)

    if not created:
        # See: https://github.com/django/django/blob/876dc0c1a7dbf569782eb64f62f339c1daeb75e0/django/contrib/sites/management.py#L11-L38
        assert site.name == "example.com"
        print("overwriting the default site")

    site.name = site.domain = settings.PRODUCTION_HOST
    site.save()


class Migration(migrations.Migration):

    replaces = [('CreeDictionary', '0001_insert_bibliographic_data'), ('CreeDictionary', '0002_change_example_site_to_cree_dictionary_site'), ('CreeDictionary', '0003_add_wordform_paradigms')]

    initial = True

    dependencies = [
        ('API', '0005_wordform_paradigm'),
        ('API', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(
            code=change_example_to_production_site,
        ),
    ]
