# Generated by Django 4.2.16 on 2024-10-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0006_drop_api_tables"),
        ("API", "0007_base_migrations_squashed"),
    ]

    operations = []
