# Generated by Django 4.2.16 on 2024-10-18 18:34

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

def change_example_to_production_site(apps, schema_editor):
    """
    Changes the example.com site to the current site domain.
    As of 2021-03-11, this is itwewina.altlab.app.
    """
    Site = apps.get_model("sites", "Site")
    site, created = Site.objects.get_or_create(pk=1)

    if not created:
        # See: https://github.com/django/django/blob/876dc0c1a7dbf569782eb64f62f339c1daeb75e0/django/contrib/sites/management.py#L11-L38
        print(f"overwriting the site {site.domain} (displayed {site.name}) with new site {settings.PRODUCTION_HOST}")

    site.name = site.domain = settings.PRODUCTION_HOST
    site.save()


class Migration(migrations.Migration):

    replaces = [('API', '0001_initial'), ('API', '0002_definition_auto_translation_source'), ('API', '0003_wordform_indexes'), ('API', '0004_more_wordform_indexes'), ('API', '0005_wordform_paradigm'), ('API', '0007_base_migrations_squashed'), ('API', '0006_drop_api_tables'), ('API', '0008_merge_20241018_1823'), ('CreeDictionary', '0001_insert_bibliographic_data'), ('CreeDictionary', '0002_change_example_site_to_cree_dictionary_site'), ('CreeDictionary', '0003_add_wordform_paradigms')]

    initial = True

    dependencies = [
        ('lexicon', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=change_example_to_production_site,
        ),
    ]
