# Generated by Django 4.2.16 on 2024-10-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0008_add_semantic_fields"),
        ("lexicon", "0009_squashed_creedictionary_migrations"),
    ]

    operations = []
