# Generated by Django 4.2.16 on 2024-11-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0010_merge_20241018_1852"),
    ]

    operations = [
        migrations.CreateModel(
            name="RapidWords",
            fields=[
                (
                    "index",
                    models.CharField(max_length=60, primary_key=True, serialize=False),
                ),
                ("domain", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="wordform",
            name="rw_domains",
        ),
    ]
