# Generated by Django 4.2.16 on 2024-11-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0011_rapidwords_remove_wordform_rw_domains"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="wordform",
            index=models.Index(fields=["slug"], name="lexicon_wor_slug_b08853_idx"),
        ),
    ]
