# Generated by Django 4.2.16 on 2024-11-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0012_wordform_lexicon_wor_slug_b08853_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordNetSynset",
            fields=[
                (
                    "name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="wordform",
            name="rapidwords",
            field=models.ManyToManyField(
                related_name="wordforms", to="lexicon.rapidwords"
            ),
        ),
        migrations.AddField(
            model_name="wordform",
            name="synsets",
            field=models.ManyToManyField(
                related_name="wordforms", to="lexicon.wordnetsynset"
            ),
        ),
    ]
