# Generated by Django 4.2.21 on 2025-05-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0016_auto_20241202_1907"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wordform",
            name="rw_indices",
        ),
        migrations.RemoveField(
            model_name="wordform",
            name="wn_synsets",
        ),
        migrations.AlterField(
            model_name="wordform",
            name="rapidwords",
            field=models.ManyToManyField(
                help_text="\n                RapidWords indices for an entry\n                ",
                related_name="wordforms",
                to="lexicon.rapidwords",
            ),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="synsets",
            field=models.ManyToManyField(
                help_text="\n                  WordNet synsets for an entry\n                  ",
                related_name="wordforms",
                to="lexicon.wordnetsynset",
            ),
        ),
    ]
