# Generated by Django 5.2.13 on 2026-05-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0017_remove_wordform_rw_indices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordform",
            name="translation_templates",
            field=models.JSONField(
                blank=True,
                help_text="\n            Translation templates available for T(name,tags) templates in\n            paradigm tables.\n        ",
                null=True,
            ),
        ),
    ]
