/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__hfst_optimized_lookup___hfst_optimized_lookup
#define __PYX_HAVE__hfst_optimized_lookup___hfst_optimized_lookup

#include "Python.h"

#ifndef __PYX_HAVE_API__hfst_optimized_lookup___hfst_optimized_lookup

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *noop(void);

#endif /* !__PYX_HAVE_API__hfst_optimized_lookup___hfst_optimized_lookup */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_hfst_optimized_lookup(void);
#else
PyMODINIT_FUNC PyInit__hfst_optimized_lookup(void);
#endif

#endif /* !__PYX_HAVE__hfst_optimized_lookup___hfst_optimized_lookup */
