#!/usr/bin/env python3

# This script is called by the deploy.altlab.dev webhook

import os
from argparse import ArgumentParser
from pathlib import Path
from subprocess import check_call


def main():
    parser = ArgumentParser()
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    def call(*call_args):
        if args.verbose:
            print(call_args)
        check_call(*call_args)

    os.chdir(Path(__file__).parent)

    call(["git", "pull"])
    call(["docker-compose", "pull"])
    call(["docker-compose", "up", "-d", "--remove-orphans"])
    call(["docker-compose", "up", "-d", "--remove-orphans"])
    call(
        [
            "docker-compose",
            "exec",
            "-T",
            "itwewina",
            "./crkeng-manage",
            "migrate",
        ]
    )


if __name__ == "__main__":
    main()
