#!/bin/sh

set -ex

# When run within Travis-CI, this script deploys the Cree Dictionary to Sapir.
URL=sapir.artsrn.ualberta.ca/redeploy/cree-dictionary

# shellcheck disable=SC2154
openssl aes-256-cbc -K "$encrypted_49b37942e026_key" -iv "$encrypted_49b37942e026_iv" -in cree-dictionary.key.enc -out cree-dictionary.key -d
http_code="$(curl --verbose -o "$TMPDIR/out.txt" -w '%{http_code}' -dsecret="$(cat cree-dictionary.key)" $URL)"
cat "$TMPDIR/out.txt" 1>&2

# Exit with an proper error code.
[ "$http_code" -eq 200 ] || exit 22
