#!/bin/sh

# When run within Travis-CI, this script deploys the Cree Dictionary to Sapir.

# shellcheck disable=SC2154
openssl aes-256-cbc -K "$encrypted_49b37942e026_key" -iv "$encrypted_49b37942e026_iv" -in cree-dictionary.key.enc -out cree-dictionary.key -d
curl --verbose --fail -dsecret="$(cat cree-dictionary.key)" sapir.artsrn.ualberta.ca/redeploy/cree-dictionary
