#!/bin/sh

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
    # On macOS and should install some brew dependencies
    # Check if all dependencies are installed:
    brew bundle check >/dev/null 2>&1 || {
        echo "==> Need to install Homebrew dependecies‥"
        brew bundle
    }
fi
