extends: 'eslint:recommended'

env:
  browser: true
  es6: true
  node: false

parserOptions:
  ecmaVersion: 2017
  sourceType: module

# These rules seem to generally follow the StandardJS style:
# https://standardjs.com/rules.html
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  camelcase:
    - error
  no-console: "warn"
