# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='InflectionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inflection',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.Word')),
                ('inflectionForms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.InflectionForm')),
            ],
            bases=('API.word',),
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.Word')),
                ('attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Attribute')),
                ('inflections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Inflection')),
            ],
            bases=('API.word',),
        ),
        migrations.AddField(
            model_name='word',
            name='definitions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Definition'),
        ),
    ]
