# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='language',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
