# Generated by Django 2.2.6 on 2019-10-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("API", "0002_auto_20191031_1843")]

    operations = [
        migrations.CreateModel(
            name="DictionarySource",
            fields=[
                (
                    "abbrv",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="What is the primary title of the dictionary source?",
                        max_length=256,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Separate multiple authors with commas. See also: editor",
                        max_length=512,
                    ),
                ),
                (
                    "editor",
                    models.CharField(
                        blank=True,
                        help_text="Who edited or compiled this volume? Separate multiple editors with commas.",
                        max_length=512,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="What year was this dictionary published?", null=True
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, help_text="What was the publisher?", max_length=128
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="What is the city of the publisher?",
                        max_length=64,
                    ),
                ),
            ],
        )
    ]
