# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20190219_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='language',
        ),
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(default='en-US', max_length=5),
            preserve_default=False,
        ),
    ]
