# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20190219_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='type',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
