# Generated by Django 2.2.9 on 2020-01-14 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("API", "0004_rename_definition_fk_lemma")]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="wordform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="definitions",
                to="API.Wordform",
            ),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="analysis",
            field=models.CharField(
                default="",
                help_text="fst analysis or the best possible generated if the source is not analyzable",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="as_is",
            field=models.BooleanField(
                default=False,
                help_text="The lemma of this wordform is not determined during the importing process.is_lemma defaults to true and lemma field defaults to self",
            ),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="full_lc",
            field=models.CharField(
                help_text="Full lexical category directly from source", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="is_lemma",
            field=models.BooleanField(
                default=False,
                help_text="The wordform is chosen as lemma. This field defaults to true if according to fst the wordform is not analyzable or it's ambiguous",
            ),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="lemma",
            field=models.ForeignKey(
                help_text="The identified lemma of this wordform. Defaults to self",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inflections",
                to="API.Wordform",
            ),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="pos",
            field=models.CharField(
                choices=[
                    ("IPV", "IPV"),
                    ("PRON", "PRON"),
                    ("N", "N"),
                    ("IPC", "IPC"),
                    ("V", "V"),
                    ("", ""),
                ],
                help_text="Part of speech parsed from source. Can be unspecified",
                max_length=4,
            ),
        ),
    ]
