# Generated by Django 2.2.6 on 2019-11-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("API", "0005_auto_20191104_1924")]

    operations = [migrations.RemoveField(model_name="definition", name="sources")]
