# Generated by Django 2.2.9 on 2020-02-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200114_2224'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wordform',
            index=models.Index(fields=['full_lc'], name='API_wordfor_full_lc_50b527_idx'),
        ),
        migrations.AddIndex(
            model_name='wordform',
            index=models.Index(fields=['pos'], name='API_wordfor_pos_b47c18_idx'),
        ),
    ]
