# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_word_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='type',
            field=models.CharField(max_length=6),
        ),
    ]
