# Generated by Django 2.1.7 on 2019-02-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20190219_0504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'select_on_save': True},
        ),
        migrations.AlterModelOptions(
            name='inflection',
            options={'select_on_save': True},
        ),
        migrations.AlterModelOptions(
            name='inflectionform',
            options={'select_on_save': True},
        ),
        migrations.AlterModelOptions(
            name='lemma',
            options={'select_on_save': True},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'select_on_save': True},
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['context'], name='API_word_context_24bbc0_idx'),
        ),
    ]
