# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20190219_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='fk_lemma',
        ),
        migrations.RemoveField(
            model_name='inflectionform',
            name='fk_inflection',
        ),
        migrations.AlterModelOptions(
            name='definition',
            options={'select_on_save': True},
        ),
        migrations.AlterModelOptions(
            name='inflection',
            options={'select_on_save': True},
        ),
        migrations.AlterModelOptions(
            name='lemma',
            options={'select_on_save': True},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'select_on_save': True},
        ),
        migrations.AddField(
            model_name='inflection',
            name='inflectionForm',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lemma',
            name='attribute',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='InflectionForm',
        ),
    ]
