# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20190220_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='InflectionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.RemoveField(
            model_name='inflection',
            name='inflectionForm',
        ),
        migrations.RemoveField(
            model_name='lemma',
            name='attribute',
        ),
        migrations.AddField(
            model_name='inflectionform',
            name='fk_inflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Inflection'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='fk_lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Lemma'),
        ),
    ]
